id: IB4645789
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T02:58:38+00:00'
last_modified: '2022-06-10T04:35:23.090442+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28732
  title: གཏེར་ཆོས། བདུད་འཇོམས་གླིང་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A04A:
      image_group_id: I4616
      title: ''
      total_pages: 652
      order: 1
      base_file: A04A.txt
    2FE6:
      image_group_id: I4617
      title: ''
      total_pages: 550
      order: 2
      base_file: 2FE6.txt
    D1E9:
      image_group_id: I4618
      title: ''
      total_pages: 628
      order: 3
      base_file: D1E9.txt
    EE04:
      image_group_id: I4619
      title: ''
      total_pages: 500
      order: 4
      base_file: EE04.txt
    81E1:
      image_group_id: I4620
      title: ''
      total_pages: 480
      order: 5
      base_file: 81E1.txt
    0D88:
      image_group_id: I4621
      title: ''
      total_pages: 602
      order: 6
      base_file: 0D88.txt
    '5713':
      image_group_id: I4622
      title: ''
      total_pages: 642
      order: 7
      base_file: 5713.txt
    4F4C:
      image_group_id: I4623
      title: ''
      total_pages: 558
      order: 8
      base_file: 4F4C.txt
    ABAF:
      image_group_id: I4624
      title: ''
      total_pages: 432
      order: 9
      base_file: ABAF.txt
    D401:
      image_group_id: I4625
      title: ''
      total_pages: 562
      order: 10
      base_file: D401.txt
    961C:
      image_group_id: I4626
      title: ''
      total_pages: 548
      order: 11
      base_file: 961C.txt
    4A77:
      image_group_id: I4627
      title: ''
      total_pages: 522
      order: 12
      base_file: 4A77.txt
    1DB6:
      image_group_id: I4628
      title: ''
      total_pages: 472
      order: 13
      base_file: 1DB6.txt
    1AEE:
      image_group_id: I4629
      title: ''
      total_pages: 476
      order: 14
      base_file: 1AEE.txt
    2AC6:
      image_group_id: I4630
      title: ''
      total_pages: 532
      order: 15
      base_file: 2AC6.txt
    '9386':
      image_group_id: I4631
      title: ''
      total_pages: 504
      order: 16
      base_file: 9386.txt
    17A5:
      image_group_id: I4632
      title: ''
      total_pages: 630
      order: 17
      base_file: 17A5.txt
    '5541':
      image_group_id: I4633
      title: ''
      total_pages: 502
      order: 18
      base_file: 5541.txt
    FC17:
      image_group_id: I4634
      title: ''
      total_pages: 375
      order: 19
      base_file: FC17.txt
    96AB:
      image_group_id: I4635
      title: ''
      total_pages: 750
      order: 20
      base_file: 96AB.txt
    2B6A:
      image_group_id: I4636
      title: ''
      total_pages: 648
      order: 21
      base_file: 2B6A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
